name: Unittests
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      
      - name: Set up
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
      
      - name: tests
        run: |
          pytest
